defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/dzkey_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/dzkey_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/dzkey
    <<: *defaults